-- ============================================================
--  UPDATE descriptions in services from calendar_2026_clean.csv
--  Auto-generated on 2026-04-13 18:32:56
--  Total updates: 365
-- ============================================================

UPDATE services SET description = '+ Нова година. Обрезание Господне. Св. Василий Велики. Св. Емилия. Св. мчк Василий Анкирски (Вас. лит.) (Василовден)' WHERE service_date = '2026-01-01';
UPDATE services SET description = 'Св. Силвестър, папа Римски. Преп. Серафим Саровски Чудотворец (Предпразненство на св. Богоявление) (Блажи се)' WHERE service_date = '2026-01-02';
UPDATE services SET description = 'Св. прор. Малахия. Св. мчк Гордий' WHERE service_date = '2026-01-03';
UPDATE services SET description = '+ Неделя преди Богоявление. Събор на св. 70 апостоли. Прпмчк Онуфрий Габровски. Преп. Теоктист' WHERE service_date = '2026-01-04';
UPDATE services SET description = 'Св. прор. Михей. Св. мчци Теопемт и Теона. Преп. Синклитикия и Аполинария (Водици) (Утреня, Царски часове, Вечерня с Вас. лит.) (Велик водосвет) (Строг пост)' WHERE service_date = '2026-01-05';
UPDATE services SET description = '+ Св. Богоявление (Утреня, Злат. лит.) (Велик водосвет) (Йордановден)' WHERE service_date = '2026-01-06';
UPDATE services SET description = '+ Св. Йоан Кръстител (Ивановден)' WHERE service_date = '2026-01-07';
UPDATE services SET description = 'Св. Григорий, еп. Български. Преп. Георги Хозевит. Св. Емилиан изповедник. Преп. Домника. Мчк Або Тбилиски' WHERE service_date = '2026-01-08';
UPDATE services SET description = 'Св. мчк Полиевкт. Св. Петър, еп. Севастийски. Преп. Евстратий' WHERE service_date = '2026-01-09';
UPDATE services SET description = 'Св. Григорий, еп. Нисийски. Преп. Дометиан, еп. Мелитински. Св. Маркиан. Св. Теофан Затворник. Блажена Теозви' WHERE service_date = '2026-01-10';
UPDATE services SET description = '+ Неделя след Богоявление. Преп. Теодосий Велики. Преп. Теодосий Антиохийски' WHERE service_date = '2026-01-11';
UPDATE services SET description = 'Св. мчца Татяна Римска. Св. Сава Сръбски. Св. мчк Мертий. Мчк Петър Авесаломит. Преп. Евпраксия' WHERE service_date = '2026-01-12';
UPDATE services SET description = 'Св. мчци Ермил и Стратоник. Св. мчк Петър Анийски. Преп. Максим Кавсокаливит. Св. Йеремия I, патр. Константинополски' WHERE service_date = '2026-01-13';
UPDATE services SET description = 'Преп. отци, избити в Синай и Раита. Св. равноап. Нина. Св. Потит Сердикийски (Отдание на Богоявление)' WHERE service_date = '2026-01-14';
UPDATE services SET description = 'Преп. отци Гавриил Лесновски, Прохор Пшински, Павел Тивейски и Йоан Колибар. Св. Герасим, патр. Александрийски' WHERE service_date = '2026-01-15';
UPDATE services SET description = 'Честни вериги на св. ап. Петър. Преп. Ромил Видински. Св. свщмчк Дамаскин Габровски' WHERE service_date = '2026-01-16';
UPDATE services SET description = '* Преп. Антоний Велики (Антоновден)' WHERE service_date = '2026-01-17';
UPDATE services SET description = '+ Неделя 12 след Неделя подир Въздвижение - на 10-те прокажени. Св. Атанасий и Кирил Александрийски. Св. Йоаким, патр. Търновски (Атанасовден)' WHERE service_date = '2026-01-18';
UPDATE services SET description = 'Преп. Макарий Египетски. Св. Марк, еп. Ефески' WHERE service_date = '2026-01-19';
UPDATE services SET description = '* Преп. Евтимий Велики. Св. Евтимий, патриарх Търновски' WHERE service_date = '2026-01-20';
UPDATE services SET description = 'Преп. Максим Изповедник. Св. мчк Неофит' WHERE service_date = '2026-01-21';
UPDATE services SET description = 'Св. ап. Тимотей. Прпмчк Анастасий Перски. Св. свщмчк Петър, еп. Български. Св. мчк Сионий Български' WHERE service_date = '2026-01-22';
UPDATE services SET description = 'Св. свщмчк Климент, еп. Анкирски. Св. мчк Агатангел. Св. Павлин, еп. Нолански' WHERE service_date = '2026-01-23';
UPDATE services SET description = 'Преп. Ксения Римлянка. Блаж. Ксения Петербургска. Преп. Филон, еп. Колпастийски' WHERE service_date = '2026-01-24';
UPDATE services SET description = '+ Неделя 15 след Неделя подир Въздвижение ¬ на Закхея. Св. Григорий Богослов, архиепископ Константинополски' WHERE service_date = '2026-01-25';
UPDATE services SET description = 'Преп. Ксенофонт и дружината му. Св. Амон. Св. Павла' WHERE service_date = '2026-01-26';
UPDATE services SET description = '* Пренасяне мощите на св. Йоан Златоуст' WHERE service_date = '2026-01-27';
UPDATE services SET description = 'Преп. Ефрем Сириец. Св. Исаак Сириец, епископ Ниневийски. Преп. Паладий Пустинник' WHERE service_date = '2026-01-28';
UPDATE services SET description = 'Пренасяне мощите на св. Игнатий Богоносец. Св. мчк Димитрий Сливенски. Св. Димитрий Гагастатис, презвитер' WHERE service_date = '2026-01-29';
UPDATE services SET description = '* Св. Трисветители велики архиереи: Василий Велики, Григорий Богослов и Йоан Златоуст. Св. свщмчк Иполит, папа Римски. Св. благоверен цар Петър Български. Преп. Сергий Къпински' WHERE service_date = '2026-01-30';
UPDATE services SET description = 'Св. безсребреници и чудотворци Кир и Йоан. Св. Серапион и Папий' WHERE service_date = '2026-01-31';
UPDATE services SET description = '+ Неделя 16 след Неделя подир Въздвижение - на Митаря и Фарисея. Св. мчк Трифон (Предпразненство на Сретение Господне) (Трифоновден)' WHERE service_date = '2026-02-01';
UPDATE services SET description = '+ Сретение Господне' WHERE service_date = '2026-02-02';
UPDATE services SET description = 'Св. Симеон Богоприимец и Анна пророчица. Св. пророк Азарий. Св. равноап Николай Японски' WHERE service_date = '2026-02-03';
UPDATE services SET description = 'Преп. Исидор Пелусийски. Св. мчк Иадор. Преп. Иасим Чудотворец (Блажи се)' WHERE service_date = '2026-02-04';
UPDATE services SET description = 'Св. мчца Агатия (Добра). Св. мчца Василиса' WHERE service_date = '2026-02-05';
UPDATE services SET description = 'Преп. Вукол, еп. Смирненски. Св. Фотий, патр. Константинополски. Преп. Варсануфий Велики. Св. Йоан Пророк. Св. мчци Доротея, Христина и Калиста (Блажи се)' WHERE service_date = '2026-02-06';
UPDATE services SET description = 'Преп. Партений, еп. Лампсакийски. Преп. Лука Еладски. Преп. Априон, еп. Кипърски' WHERE service_date = '2026-02-07';
UPDATE services SET description = '+ Неделя 17 след Неделя подир Въздвижение ¬ на Блудния син. Св. вмчк Теодор Стратилат. Св. прор. Захария Сърповидец' WHERE service_date = '2026-02-08';
UPDATE services SET description = 'Св. мчк Никифор (Отдание на Сретение Господне)' WHERE service_date = '2026-02-09';
UPDATE services SET description = '* Св. свщмчк Харалампий Чудотворец. Св. мчца Валентина' WHERE service_date = '2026-02-10';
UPDATE services SET description = '* Св. свщмчк Власий, еп. Севастийски. Св. мчк Георги Софийски, Нови' WHERE service_date = '2026-02-11';
UPDATE services SET description = 'Св. Мелетий, архиеп. Антиохийски. Св. Антоний, патр. Константинополски' WHERE service_date = '2026-02-12';
UPDATE services SET description = 'Преп. Мартиниан. Св. Евлогий, архиеп. Александрийски. Преп. Зоя (Живка) и Фотина (Светлана)' WHERE service_date = '2026-02-13';
UPDATE services SET description = '* Успение на св. Кирил Славянобългарски. Преп. Авксентий. (Задушница)' WHERE service_date = '2026-02-14';
UPDATE services SET description = '+ Неделя Месопустна (Месни заговезни). Св. ап. Онисим. Преп. Евсевий Сирийски' WHERE service_date = '2026-02-15';
UPDATE services SET description = 'Св. мчци Памфил и Порфирий. Св. Флавиан, патр. Константинополски' WHERE service_date = '2026-02-16';
UPDATE services SET description = 'Св. вмчк Теодор Тирон. Преп. Роман Търновски' WHERE service_date = '2026-02-17';
UPDATE services SET description = 'Св. Лъв, папа Римски. Св. Агапит Изповедник, еп. Синадски (Службата е великопостна) (Блажи се риба и млечни храни)' WHERE service_date = '2026-02-18';
UPDATE services SET description = 'Св. ап. Архип и Филимон от 70-те, и мчца и равноап. Апфия. Преп. Доситей' WHERE service_date = '2026-02-19';
UPDATE services SET description = 'Св. Лъв, еп. Катански. Св. Агатон, папа Римски. Св. свщмчк Садок, еп. Персийски и 128 мъченици с него. Преп. Плотин (Службата е великопостна) (Блажи се риба и млечни храни)' WHERE service_date = '2026-02-20';
UPDATE services SET description = 'Преп. Тимотей. Св. Евстатий, архиеп. Антиохийски' WHERE service_date = '2026-02-21';
UPDATE services SET description = '+ Неделя Сиропустна (Сирни заговезни). Намиране честните мощи на св. мчци в Евгения' WHERE service_date = '2026-02-22';
UPDATE services SET description = 'Св. свщмчк Поликарп, еп. Смирненски. Преп. Александър, първоначалник на обителта на незаспиващите. (Вечерта - Велико повечерие с канона на св. Андрей Критски, I част)' WHERE service_date = '2026-02-23';
UPDATE services SET description = '* 1-во и 2-ро намиране честната глава на св. Йоан Кръстител (Прежд. лит.) (Вечерта - Велико повечерие с канона на св. Андрей Критски, II част)' WHERE service_date = '2026-02-24';
UPDATE services SET description = 'Св. Тарасий, архиеп. Константинополски (Прежд. лит.) (Вечерта - Велико повечерие с канона на св. Андрей Критски, III част)' WHERE service_date = '2026-02-25';
UPDATE services SET description = '*Св. Серафим Софийски Чудотворец. Св. Порфирий, еп. Газки. Св. мчк Севастиан (Вечерта - Велико повечерие с канона на св. Андрей Критски, IV част)' WHERE service_date = '2026-02-26';
UPDATE services SET description = 'Преп. Прокопий Декаполит, изповедник (Прежд. лит.) (Вечерта - Малко повечерие с Богородичен акатист, I статия)' WHERE service_date = '2026-02-27';
UPDATE services SET description = '*Тодорова събота. Преп. Василий Изповедник. Св. мчца Кирана Солунска (Злат. лит.)' WHERE service_date = '2026-02-28';
UPDATE services SET description = '+ 1 Неделя на Великия пост - Православна. Св. прпмчца Евдокия Илиополска' WHERE service_date = '2026-03-01';
UPDATE services SET description = 'Св. свщмчк Теодот, еп. Киринейски. Мчца Евталия. Преп. Агатон Египетски' WHERE service_date = '2026-03-02';
UPDATE services SET description = 'Св. мчци Евтропий, Клеоник и Василиск. Ден на Освобождението на България от османско иго – Национален празник' WHERE service_date = '2026-03-03';
UPDATE services SET description = 'Преп. Герасим Йордански (Прежд. лит.)' WHERE service_date = '2026-03-04';
UPDATE services SET description = 'Св. мчци Конон Исаврийски и Йоан Българин' WHERE service_date = '2026-03-05';
UPDATE services SET description = 'Св. 42 мчци в Амория (Прежд. лит.) (Вечерта - Малко повечерие с Богородичен акатист, II статия)' WHERE service_date = '2026-03-06';
UPDATE services SET description = 'Св. свщмчци Василий, Ефрем, Капитон и др. епископи Херсонски (Злат. лит.)' WHERE service_date = '2026-03-07';
UPDATE services SET description = '+ 2 Неделя на Великия пост - Св. Григорий Палама. Преп. Теофилакт, еп. Никомидийски' WHERE service_date = '2026-03-08';
UPDATE services SET description = '*Св. 40 мчци Севастийски. Св. мчк Исихий Доростолски. (Прежд. лит.)' WHERE service_date = '2026-03-09';
UPDATE services SET description = 'Св. мчци Кодрат и Галина' WHERE service_date = '2026-03-10';
UPDATE services SET description = '*Св. Софроний, еп. Врачански. Св. Софроний, патр. Йерусалимски. (Прежд. лит.)' WHERE service_date = '2026-03-11';
UPDATE services SET description = 'Преп. Теофан Изповедник. Св. Григорий Двоеслов. Преп. Симеон, Нови Богослов' WHERE service_date = '2026-03-12';
UPDATE services SET description = 'Св. Никифор, патр. Константинополски (Прежд. лит.) (Вечерта - Малко повечерие с Богородичен акатист, III статия)' WHERE service_date = '2026-03-13';
UPDATE services SET description = 'Преп. Бенедикт Нурсийски (Злат. лит.)' WHERE service_date = '2026-03-14';
UPDATE services SET description = '+ 3 Неделя на Великия пост - Кръстопоклонна. Св. мчк Агапий и 6-те мъченици с него. Св. мчк. Никандър' WHERE service_date = '2026-03-15';
UPDATE services SET description = 'Св. ап. Аристовул. Св. мчци Савин и Папа' WHERE service_date = '2026-03-16';
UPDATE services SET description = 'Преп. Алексий, човек Божи' WHERE service_date = '2026-03-17';
UPDATE services SET description = 'Св. Кирил, патриарх Йерусалимски. (Прежд. лит.)' WHERE service_date = '2026-03-18';
UPDATE services SET description = 'Св. мчци Хрисант и Дария' WHERE service_date = '2026-03-19';
UPDATE services SET description = 'Преп. отци, избити в манастира „Св. Сава” (Прежд. лит.) (Вечерта - Малко повечерие с Богородичен акатист, IV статия)' WHERE service_date = '2026-03-20';
UPDATE services SET description = 'Преп. Яков, епископ и изповедник (Злат. лит.)' WHERE service_date = '2026-03-21';
UPDATE services SET description = '+ 4 Неделя на Великия пост - Преп. Йоан Лествичник. Св. свщмчк Василий, презвитер Анкирски' WHERE service_date = '2026-03-22';
UPDATE services SET description = 'Св. свщмчк Никон. Св. прпмчк Лука Одрински. (Вечерта - Малко повечерие с целия канон на св. Андрей Критски)' WHERE service_date = '2026-03-23';
UPDATE services SET description = 'Преп. Захария. Св. Артемий, еп. Солунски. (Вечерта – Велика вечерня)' WHERE service_date = '2026-03-24';
UPDATE services SET description = '+ Благовещение (Утреня и Злат. лит.), утр. ев. на празника, ап. Евр. 2:11-18 (с.481), лит. ев. Лк 1:24-38 (Вечерта - отдание на празника) (Разрешава се риба)' WHERE service_date = '2026-03-25';
UPDATE services SET description = 'Събор на св. архангел Гавриил. Св. мчк Георги Софийски, Стари' WHERE service_date = '2026-03-26';
UPDATE services SET description = 'Св. мчца Матрона Солунска (Прежд. лит.) (Вечерта - Малко повечерие с целия Богородичен канон и акатист)' WHERE service_date = '2026-03-27';
UPDATE services SET description = '*Акатистна събота. Чудотворна икона на Пресв. Богородица „Златна ябълка“. Преп Иларион Нови, изповедник и преп. Стефан, изповедник. Свщмчци Георги, еп. Загорски и Петър, презв. Мъгленски. Св. мчк Енравота-Боян, княз Български (Злат. лит.)' WHERE service_date = '2026-03-28';
UPDATE services SET description = '+ 5 Неделя на Великия пост ¬ Преп. Мария Египетска. Преп. Марк, еп. Аретусийски и св. Кирил, дякон' WHERE service_date = '2026-03-29';
UPDATE services SET description = 'Преп. Йоан Синайски - Лествичник' WHERE service_date = '2026-03-30';
UPDATE services SET description = 'Св. свщмчк Ипатий, еп. Гангърски' WHERE service_date = '2026-03-31';
UPDATE services SET description = 'Преп. Мария Египетска. Св. мчк Аврамий Български (Прежд. лит.)' WHERE service_date = '2026-04-01';
UPDATE services SET description = 'Преп. Тит Чудотворец. Св. мчци Амфиан и Едесий' WHERE service_date = '2026-04-02';
UPDATE services SET description = 'Преп. Никита Изповедник, игумен Мидикийски (Прежд. лит.) (Вечерта - Малко повечерие с канона от Триода)' WHERE service_date = '2026-04-03';
UPDATE services SET description = '*Лазарова събота. Преп. Йосиф Песнописец. Преп. Георги в Малея. Св. свщмчк Никита Серски (Злат. лит.)' WHERE service_date = '2026-04-04';
UPDATE services SET description = '+ 6 Неделя на Великия пост – Вход Господен в Йерусалим - Връбница - Цветница. Св. мчци Теодул и Агатопод. (Всичко на празника) (Злат. лит.) утр. ев. Мт 21:1-11, 15-17 (с. 187), ап. Фил. 4:4-9 (с. 334), лит. ев. Ин 12: 1-18 (с. 187) (Вечерта - Последование на Жениха). (Разрешава се риба)' WHERE service_date = '2026-04-05';
UPDATE services SET description = '*Велики понеделник. Йосиф Прекрасни. Успение на св. Методий Славянобългарски. Св. Евтихий, патр. Константинополски. Св. мчци Тимотей и Диоген. (Прежд. лит.) (Вечерта - Последование на Жениха)' WHERE service_date = '2026-04-06';
UPDATE services SET description = '*Велики вторник. Десетте Девици. Преп. Георги, еп. Митилински. (Прежд. лит.) (Вечерта - Последование на Жениха)' WHERE service_date = '2026-04-07';
UPDATE services SET description = '*Велика сряда. Помазването на Господа с миро. Св. апли Иродион, Агав, Руф и др. (Прежд. лит.) (Вечерта - Малко повечерие)' WHERE service_date = '2026-04-08';
UPDATE services SET description = '*Велики четвъртък. Тайната вечеря. Св. мчк Евпсихий. (Утреня, общ маслосвет, Вечерня със св. Василиева литургия) (Вечерта - Последование на 12-те евангелия)' WHERE service_date = '2026-04-09';
UPDATE services SET description = '*Велики петък. Св. страдания Господни. Св. мчци Терентий и дружина. (Царски часове, Вечерня, с изнасяне на св. Плащаница) (Вечерта - Опело Христово)' WHERE service_date = '2026-04-10';
UPDATE services SET description = '*Велика събота. Слизането на Господа в ада. Св. свщмчк Антипа, еп. Пергамски. (Сутринта - Вечерня със св. Василиева литургия)' WHERE service_date = '2026-04-11';
UPDATE services SET description = '+ Възкресение Христово ¬ Пасха. Утр. ев. Мат. 28: 1-9 (с. 9), ап. Деян. 1: 1-8 (с. 1), лит. ев. Ин 1: 1-17 (с. 10) (Вечерня в първия ден на Пасха)' WHERE service_date = '2026-04-12';
UPDATE services SET description = '+ Възкресение Христово. Св. свщмчк Артемон, презвитер Лаодикийски' WHERE service_date = '2026-04-13';
UPDATE services SET description = '+ Възкресение Христово. Св. Мартин, папа Римски' WHERE service_date = '2026-04-14';
UPDATE services SET description = '*Светла сряда. Св. апли Аристарх, Пуд и Трофим (Блажи се)' WHERE service_date = '2026-04-15';
UPDATE services SET description = '*Светли четвъртък. Св. мчци Агапия, Ирина и Хиония' WHERE service_date = '2026-04-16';
UPDATE services SET description = '*Светли петък. Живоприемни източник. Преп. Симеон Персидски. Преп. Акакий, еп. Мелитински. (Блажи се)' WHERE service_date = '2026-04-17';
UPDATE services SET description = '*Светла събота. Преп. Йоан. Св. мчк Виктор' WHERE service_date = '2026-04-18';
UPDATE services SET description = '+ 2 Неделя след Пасха ¬ Томина. Преп. Йоан Ветхопещерник' WHERE service_date = '2026-04-19';
UPDATE services SET description = 'Преп. Теодор Трихина. Св. Григорий и Анастасий, патр. Антиохийски' WHERE service_date = '2026-04-20';
UPDATE services SET description = 'Св. свщмчци Януарий и Теодор в Пергия' WHERE service_date = '2026-04-21';
UPDATE services SET description = 'Преп. Теодор Сикеот. Преп. Виталий' WHERE service_date = '2026-04-22';
UPDATE services SET description = 'Св. мчца Александра. Св. мчк Лазар Български' WHERE service_date = '2026-04-23';
UPDATE services SET description = 'Св. мчк Сава Стратилат Римски и 70 войни с него' WHERE service_date = '2026-04-24';
UPDATE services SET description = '*Св. ап. и ев. Марк' WHERE service_date = '2026-04-25';
UPDATE services SET description = '+ 3 Неделя след Пасха ¬ на св. Мироносици. Св. свщмчк Василий, еп. Амасийски' WHERE service_date = '2026-04-26';
UPDATE services SET description = 'Св. свщмчк Симеон, брат Господен по плът' WHERE service_date = '2026-04-27';
UPDATE services SET description = 'Св. апли Иасон и Сосипатър' WHERE service_date = '2026-04-28';
UPDATE services SET description = 'Св. 9 мчци в Кизик. Преп. Мемнон Чудотворец' WHERE service_date = '2026-04-29';
UPDATE services SET description = '*Св. ап. Яков Зеведеев. Преп. Климент Песнописец. Св. Донат, еп. Еврийски' WHERE service_date = '2026-04-30';
UPDATE services SET description = 'Св. прор. Йеремия. Прпмчк Акакий Серски. Св. благов. Тамара, царица Грузинска' WHERE service_date = '2026-05-01';
UPDATE services SET description = '*Св. цар Борис-Михаил. Св. Атанасий Велики' WHERE service_date = '2026-05-02';
UPDATE services SET description = '+ 4 Неделя след Пасха ¬ на Разслабления. Св. мчци Тимотей и Мавра. Св. мчк Ахмед. Преп. Петър, еп. Аргоски чудотворец' WHERE service_date = '2026-05-03';
UPDATE services SET description = 'Св. прпмчца Пелагия. Св. Силван, еп. Кесарийски' WHERE service_date = '2026-05-04';
UPDATE services SET description = 'Св. вмчца Ирина. Преп. Иеракс Египетски' WHERE service_date = '2026-05-05';
UPDATE services SET description = '+ Св. вмчк Георги Победоносец. Преполовение. Св. прав. Иов Многострадални. (Гергьовден)' WHERE service_date = '2026-05-06';
UPDATE services SET description = 'Св. мчк Акакий. Св. Авив, еп. Некрески' WHERE service_date = '2026-05-07';
UPDATE services SET description = '*Св. ап. и ев. Йоан Богослов. Преп. Арсений Велики' WHERE service_date = '2026-05-08';
UPDATE services SET description = '*Пренасяне мощите на св. Николай, Мирликийски Чудотворец. Събор на св. Новоселски мъченици. Св. прор. Исаия. Св. мчк Христофор' WHERE service_date = '2026-05-09';
UPDATE services SET description = '+ 5 Неделя след Пасха ¬ на Самарянката. Св. ап. Симон Зилот. Възстановяване на Българската патриаршия' WHERE service_date = '2026-05-10';
UPDATE services SET description = '+ Св. равноапостолни Методий и Кирил, славянобългарски учители. Св. свщмчк Мокий' WHERE service_date = '2026-05-11';
UPDATE services SET description = 'Св. Епифаний, еп. Кипърски и св. Герман, патриарх Константинополски. (Молебен за здравния работник)' WHERE service_date = '2026-05-12';
UPDATE services SET description = 'Св. мчца Гликерия девица. Св. мчк Лаодикий. Св. Павсикакий, еп. Синадски. Св. Георги Изповедник' WHERE service_date = '2026-05-13';
UPDATE services SET description = 'Св. Исидор. Св. мчк Йоан Български. Св. Райко (Йоан) Шуменски' WHERE service_date = '2026-05-14';
UPDATE services SET description = 'Преп. Пахомий Велики. Преп. Ахилий, еп. Лариски' WHERE service_date = '2026-05-15';
UPDATE services SET description = 'Преп. Теодор Освещени. Св. преп. отци, избити в манастира „Св. Сава”' WHERE service_date = '2026-05-16';
UPDATE services SET description = '+ 6 Неделя след Пасха ¬ на Слепия. Св. мчк Николай Софийски. Събор на св. Баташки мъченици. Св. ап. Андроник' WHERE service_date = '2026-05-17';
UPDATE services SET description = 'Св. мчк Теодот Анкирски. Св. мчци Петър, Дионисий и дружината им. Св. 7 девици' WHERE service_date = '2026-05-18';
UPDATE services SET description = 'Св. свщмчк Патрикий, еп. Брусенски. Св. мчк Калуф Египтянин' WHERE service_date = '2026-05-19';
UPDATE services SET description = '*Отдание на Пасха. Св. мчк Талалей. Св. равноапостолна Лидия' WHERE service_date = '2026-05-20';
UPDATE services SET description = '+ Възнесение Господне (Спасовден). Св. велики равноапостолни царе Константин и Елена' WHERE service_date = '2026-05-21';
UPDATE services SET description = 'Св. мчк Василиск. Св. мчк Йоан-Владимир, княз Български, чудотворец' WHERE service_date = '2026-05-22';
UPDATE services SET description = 'Св. Михаил Синадски. Прпмчк Михаил' WHERE service_date = '2026-05-23';
UPDATE services SET description = '+ 7 Неделя след Пасха - на св. Отци от Първия вселенски събор. Преп. Симеон Дивногорски' WHERE service_date = '2026-05-24';
UPDATE services SET description = '*3-то намиране честната глава на св. Йоан Кръстител' WHERE service_date = '2026-05-25';
UPDATE services SET description = '*Св. ап. Карп. Св. мчк Георги Софийски, Най-нови' WHERE service_date = '2026-05-26';
UPDATE services SET description = 'Св. свщмчк Терапонтий. Св. мчк Терапонтий Софийски. Св. Йоан Руски, изповедник' WHERE service_date = '2026-05-27';
UPDATE services SET description = 'Преп. Никита, еп. Халкидонски. Преп. Софроний Български' WHERE service_date = '2026-05-28';
UPDATE services SET description = 'Св. Александър, патр. Александрийски. Св. мчца Теодосия девица (Отдание на Възнесение)' WHERE service_date = '2026-05-29';
UPDATE services SET description = 'Преп. Исакий Далматски. Св. Емилия (Задушница)' WHERE service_date = '2026-05-30';
UPDATE services SET description = '+ 8 Неделя след Пасха - Петдесетница. (Всичко на празника), утр. ев. Ин 20: 19-23 (с. 44), ап. Деян. 2:1-11 (с. 61), лит. ев. Ин 7:37-52, 8:12 (с. 44)' WHERE service_date = '2026-05-31';
UPDATE services SET description = '+ Свети Дух. Св. мчк Юстин Философ. Св. мчци Юстин и дружината му' WHERE service_date = '2026-06-01';
UPDATE services SET description = 'Св. Никифор Изповедник, патр. Константинополски. Прпмчк Еразъм Охридски' WHERE service_date = '2026-06-02';
UPDATE services SET description = 'Мчци Лукилиан, Клавдий, Ипатий, Павел, Дионисий и мъченица Павла Девица. Св. Маркелин. Преп. Атанасий Чудотворец (Блажи се)' WHERE service_date = '2026-06-03';
UPDATE services SET description = 'Св. Митрофан, патр. Константинополски. Св. мчци Фронтасий, Северин и др. Св. свщмчк Астий, еп. Дирахийски. Св. мчк Конкордий' WHERE service_date = '2026-06-04';
UPDATE services SET description = 'Св. свщмчк Доротей, еп. Тирски. Преп. Петър Корицки (Блажи се)' WHERE service_date = '2026-06-05';
UPDATE services SET description = 'Преп. Висарион Египетски Чудотворец. Преп. Иларион Нови. (Отдание на Петдесетница)' WHERE service_date = '2026-06-06';
UPDATE services SET description = '+ 1 Неделя след Петдесетница¬ - на Всички светии. Св. свщмчк Теодот, еп. Анкирски. Св. мчца Валерия' WHERE service_date = '2026-06-07';
UPDATE services SET description = 'Св. Ефрем, патр. Антиохийски. Пренасяне мощите на св. вмчк Теодор Стратилат. Св. мчци Марк и Юлий Доростолски (Начало на Петровите пости)' WHERE service_date = '2026-06-08';
UPDATE services SET description = 'Св. Кирил, архиеп. Александрийски' WHERE service_date = '2026-06-09';
UPDATE services SET description = 'Св. свщмчк Тимотей, еп. Брусенски' WHERE service_date = '2026-06-10';
UPDATE services SET description = '*Св. апли Вартоломей и Варнава. Св. Лука Симферополски (Войно-Ясенецки). Св. Богородица “Достойно есть”' WHERE service_date = '2026-06-11';
UPDATE services SET description = 'Преп. Онуфрий Велики. Преп. Петър Атонски' WHERE service_date = '2026-06-12';
UPDATE services SET description = 'Св. мчца Акилина. Св. Трифилий, еп. Никозийски' WHERE service_date = '2026-06-13';
UPDATE services SET description = '+ 2 Неделя след Петдесетница - на Всички български светии. Св. прор. Елисей. Св. Методий, патр. Константинополски' WHERE service_date = '2026-06-14';
UPDATE services SET description = 'Св. прор. Амос. Св. мчк Исихий Доростолски. Св. Ефрем, патр. Сръбски, българин' WHERE service_date = '2026-06-15';
UPDATE services SET description = 'Св. Тихон, еп. Аматунтски, чудотворец. Свщмчк Тигрий, презвитер и св. мчк. Евтропий, четец. Пренасяне мощите на св. Теофан Затворник' WHERE service_date = '2026-06-16';
UPDATE services SET description = 'Св. мчци Мануил, Савел и Исмаил. Св. мчк Манасий Габровски. Св. ап. Аетий' WHERE service_date = '2026-06-17';
UPDATE services SET description = 'Св. мчци Леонтий, Ипатий и Теодул' WHERE service_date = '2026-06-18';
UPDATE services SET description = '*Св. ап. Иуда, брат Господен. Преп. Паисий Хилендарски. Преп. Паисий Велики. Св. мчк Зосима Созополски. Св. Йоан Шанхайски' WHERE service_date = '2026-06-19';
UPDATE services SET description = '*Преп. Наум Охридски. Св. свщмчк Методий, епископ Патарски. Св. Калист, патр. Константинополски' WHERE service_date = '2026-06-20';
UPDATE services SET description = '+ 3 Неделя след Петдесетница. Събор на светите Доростолски мъченици. Св. мчк Юлиан Тарсийски. Св. свщмчк Терентий, епископ Иконийски' WHERE service_date = '2026-06-21';
UPDATE services SET description = 'Св. свщмчк Евсевий, еп. Самосатски. Св. мчци Зинон и Зина. Св. мчци Галактион и Юлиания' WHERE service_date = '2026-06-22';
UPDATE services SET description = 'Св. мчца Агрипина. Св. преп. Антоний и Йоаникий' WHERE service_date = '2026-06-23';
UPDATE services SET description = '*Рождение на св. Йоан Кръстител (Еньовден). Св. Никита, еп. Ремесиански' WHERE service_date = '2026-06-24';
UPDATE services SET description = '*Св. прпмчк Прокопий Варненски. Св. прпмчца Феврония. Преп. Дионисий Атонски' WHERE service_date = '2026-06-25';
UPDATE services SET description = 'Преп. Давид Солунски. Преп. Давид Български' WHERE service_date = '2026-06-26';
UPDATE services SET description = 'Преп. Сампсон Странноприимец' WHERE service_date = '2026-06-27';
UPDATE services SET description = '+ 4 Неделя след Петдесетница. Пренасяне мощите на св. безсребреници и чудотворци Кир и Йоан' WHERE service_date = '2026-06-28';
UPDATE services SET description = '+ Св. първовърховни апостоли Петър и Павел (Петровден)' WHERE service_date = '2026-06-29';
UPDATE services SET description = '*Събор на св. славни и всехвални 12 апостоли. Преп. Гервасий Параскевопулос' WHERE service_date = '2026-06-30';
UPDATE services SET description = '*Възвръщане честните мощи на преп. Йоан Рилски чудотворец. Св. безсребреници Козма и Дамян от Рим' WHERE service_date = '2026-07-01';
UPDATE services SET description = '*Полагане честната дреха на Пресвета Богородица във Влахерна' WHERE service_date = '2026-07-02';
UPDATE services SET description = 'Св. мчк Иакинт. Св. Анатолий, патр. Константинополски' WHERE service_date = '2026-07-03';
UPDATE services SET description = 'Св. Андрей, архиепископ Критски. Св. прав. Марта' WHERE service_date = '2026-07-04';
UPDATE services SET description = '+ 5 Неделя след Петдесетница. Преп. Атанасий Атонски. Преп. Сергий Радонежки, чудотворец' WHERE service_date = '2026-07-05';
UPDATE services SET description = 'Преп. Сисой Велики. Св. свщмчк Валентин, презвитер Римски' WHERE service_date = '2026-07-06';
UPDATE services SET description = '*Св. вмчца Неделя. Преп. Тома Малейски. Преп. Акакий' WHERE service_date = '2026-07-07';
UPDATE services SET description = 'Св. вмчк Прокопий. Преп. Теофил Мироточиви' WHERE service_date = '2026-07-08';
UPDATE services SET description = 'Св. свщмчк Панкратий, еп. Тавроменийски' WHERE service_date = '2026-07-09';
UPDATE services SET description = 'Св. 45 мчци в Никопол Арменски' WHERE service_date = '2026-07-10';
UPDATE services SET description = '*Св. вмчца Евфимия Всехвална. Св. равноап. княгиня Олга. Преп. Никодим Албански. Св. Софроний Светогорец (Сахаров)' WHERE service_date = '2026-07-11';
UPDATE services SET description = '+ 6 Неделя след Петдесетница. Преп. Паисий Светогорец. Света Богородица – „Троеручица“. Св. мчци Прокъл и Иларий. Св. правед. Вероника' WHERE service_date = '2026-07-12';
UPDATE services SET description = 'Събор на св. архангел Гавриил. Преп. Стефан Саваит' WHERE service_date = '2026-07-13';
UPDATE services SET description = 'Св. ап. Акила. Преп. Никодим Светогорец' WHERE service_date = '2026-07-14';
UPDATE services SET description = '*Св. мчци Кирик и Юлита. Св. равноап. велик княз Владимир' WHERE service_date = '2026-07-15';
UPDATE services SET description = 'Св. свщмчк Атиноген, еп. Севастийски и 10-те му ученици. Св. мчца Юлия девица. Св. мчк Йоан Търновски. Събор на св. свщмчци Николаос Хеше и синът му Хабиб' WHERE service_date = '2026-07-16';
UPDATE services SET description = '*Св. вмчца Марина' WHERE service_date = '2026-07-17';
UPDATE services SET description = 'Св. мчк Иакинт в Амастрида. Св. мчк Емилиан Доростолски. Преп. Гавриилия (Папаяни)' WHERE service_date = '2026-07-18';
UPDATE services SET description = '+ 7 Неделя след Петдесетница - на св. Отци от 6-те Вселенски събори. Преп. Макрина. Преп. Дий' WHERE service_date = '2026-07-19';
UPDATE services SET description = '+ Св. прор. Илия (Илинден), ап. Иак. 5:10-20 (с. 523), лит. ев. Лк 4:22-30 (с. 358)' WHERE service_date = '2026-07-20';
UPDATE services SET description = 'Св. прор. Иезекиил. Преп. Симеон, юродив заради Христа и преп. Йоан' WHERE service_date = '2026-07-21';
UPDATE services SET description = 'Св. мироносица и равноапостолна Мария Магдалина. Възвръщане мощите на св. свщмчк Фока' WHERE service_date = '2026-07-22';
UPDATE services SET description = 'Св. мчци Трофим, Теофил и другарите им. Св. свщмчк Аполинарий, еп. Равенийски' WHERE service_date = '2026-07-23';
UPDATE services SET description = 'Св. вмчца Христина. Св. мчци князе Борис и Глеб' WHERE service_date = '2026-07-24';
UPDATE services SET description = '*Успение на св. Анна. Св. дякониса Олимпиада и Евпраксия девица' WHERE service_date = '2026-07-25';
UPDATE services SET description = '+ 8 Неделя след Петдесетница. Св. прпмчца Параскева Римлянка. Св. свщмчк Ермолай, Ермил и Ермократ Никомидийски' WHERE service_date = '2026-07-26';
UPDATE services SET description = '*Св. вмчк Пантелеймон. Св. Седмочисленици. Успение на св. Климент, архиеп. Охридски' WHERE service_date = '2026-07-27';
UPDATE services SET description = 'Св. апли и дякони Прохор, Никанор, Тимон и Пармен. Чудотворна икона на Св. Богородица – Зографска Акатистна' WHERE service_date = '2026-07-28';
UPDATE services SET description = '*Св. свщмчк Висарион Смоленски. Св. мчк Калиник. Св. мчца Серафима девица' WHERE service_date = '2026-07-29';
UPDATE services SET description = 'Св. апли от 70-те Сила, Силуан, Крискент, Епенет и Андроник. Св. Валентин, еп. Интерамски (Богородични заговезни)' WHERE service_date = '2026-07-30';
UPDATE services SET description = 'Св. праведен Евдоким Кападокийски. Св. мчца Юлита и св. Йосиф Ариматейски' WHERE service_date = '2026-07-31';
UPDATE services SET description = '*Произхождение (изнасяне) на св. Кръст. Св. мчци 7 братя Макавеи. Св. Соломония. Св. Елеазар. (Водосвет) (Начало на Богородичния пост)' WHERE service_date = '2026-08-01';
UPDATE services SET description = '+ 9 Неделя след Петдесетница. Пренасяне мощите на св. архидякон Стефан. Св. свщмчк Стефан, папа Римски' WHERE service_date = '2026-08-02';
UPDATE services SET description = 'Преп. Исакий, Фавст и Далмат (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-03';
UPDATE services SET description = 'Св. 7 отроци в Ефес. Св. прпмчца Евдокия (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-04';
UPDATE services SET description = 'Св. мчк Евсигний (Предпр. на Преображение Господне)' WHERE service_date = '2026-08-05';
UPDATE services SET description = '+ Преображение Господне (Разрешава се риба) (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-06';
UPDATE services SET description = 'Св. прпмчк Дометий Персийски. Св. прпмчца Потамия, чудотворица. Св. Наркис, патр. Йерусалимски (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-07';
UPDATE services SET description = 'Св. Емилиан изповедник, еп. Кизически. Св. Мирон, еп. Критски, чудотворец. Св. Трендафил Загорски. Св. мчк. Анастасий Струмишки' WHERE service_date = '2026-08-08';
UPDATE services SET description = '+ 10 Неделя след Петдесетница. Неделя след Преображение. Св. ап. Матия. Преп. Псой. Св. Самуил, презв. Едески' WHERE service_date = '2026-08-09';
UPDATE services SET description = 'Св. мчк и архидякон Лаврентий (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-10';
UPDATE services SET description = 'Св. мчк и архидякон Евпъл. Св. мчца Сосана девица (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-11';
UPDATE services SET description = 'Св. мчци Фотий и Аникита. Преп. Паламон Египетски. Св. свщмчк Александър, еп. Комански. Св. мчци Памфил и Капитон. (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-12';
UPDATE services SET description = 'Преп. Максим Изповедник. Св. Тихон, еп. Задонски (Отдание на Преображение Господне) (вечерта - Вечерня с Молебен канон на Пресвета Богородица)' WHERE service_date = '2026-08-13';
UPDATE services SET description = 'Св. прор. Михей (Предпр. на Успение Богородично)' WHERE service_date = '2026-08-14';
UPDATE services SET description = '+ Успение на Пресвета Богородица' WHERE service_date = '2026-08-15';
UPDATE services SET description = '+ 11 Неделя след Петдесетница. Пренасяне на неръкотворния образ (св. убрус) на Господ Иисус Христос. (Неделя след Успение Богородично). Св. мчк Диомид. Преп. Йоаким Осоговски. Св. преп. Херимон Египетски. Св. прпмчк Никодим Метеорски' WHERE service_date = '2026-08-16';
UPDATE services SET description = 'Св. мчк Мирон. Преп. Алипий иконописец. Преп. Атанасий Хамакиотис' WHERE service_date = '2026-08-17';
UPDATE services SET description = '*Успение на преп. Йоан Рилски Чудотворец. Св. мчци Флор и Лавър' WHERE service_date = '2026-08-18';
UPDATE services SET description = 'Св. мчк Андрей Стратилат и с него 2593 мъченици. Преп. Теофан Атонски Нови' WHERE service_date = '2026-08-19';
UPDATE services SET description = 'Св. прор. Самуил. Св. 37 мчци Пловдивски' WHERE service_date = '2026-08-20';
UPDATE services SET description = 'Св. ап. Тадей. Св. мчци Васа Хелеспонтска и Васа Солунска. Св. свщмчк Симеон Самоковски' WHERE service_date = '2026-08-21';
UPDATE services SET description = 'Св. мчк Агатоник, Зотик и Теопрепий и др. Св. мчца Евлалия девица. Св. преп. Антуса' WHERE service_date = '2026-08-22';
UPDATE services SET description = '+ 12 Неделя след Петдесетница. Св. мчк Луп. Св. Ириней, еп. Лионски. (Отдание на Успение Богородично) Гл. 3, утр. ев. 1, ап. 1 Кор. 15:1-11 (с. 149), лит. ев. Мт 19:16-26 (с. 83) [на отдание ап. Фил. 2:5-11 (с. 535), лит. ев. Лк 10:38-42, 11:27-28 (с. 365)]' WHERE service_date = '2026-08-23';
UPDATE services SET description = 'Св. свщмчк Евтих. Преп. Георги Лимниот. Св. мчк Татион. Св. Козма Етолийски. Св. Дионисий Егински' WHERE service_date = '2026-08-24';
UPDATE services SET description = 'Възвръщане честните мощи на св. ап. Вартоломей. Св. ап. Тит' WHERE service_date = '2026-08-25';
UPDATE services SET description = 'Св. мчци Адриан и Наталия' WHERE service_date = '2026-08-26';
UPDATE services SET description = 'Преп. Пимен Велики. Св. Фанурий' WHERE service_date = '2026-08-27';
UPDATE services SET description = 'Преп. Моисей Мурин' WHERE service_date = '2026-08-28';
UPDATE services SET description = '*Отсичане честната глава на св. Йоан Предтеча и Кръстител.. (Пост)' WHERE service_date = '2026-08-29';
UPDATE services SET description = '+ 13 Неделя след Петдесетница. Пренасяне честните мощи на св. Александър Невски. Св. Александър, Йоан и Павел, патриарси Константинополски' WHERE service_date = '2026-08-30';
UPDATE services SET description = '*Полагане честния пояс на Пресвета Богородица. Св. свщмчк Киприан, еп. Картагенски. Св. Генадий, патриарх Константинополски' WHERE service_date = '2026-08-31';
UPDATE services SET description = '*Начало на Индикта - Църковната нова година. Преп. Симеон Стълпник. Преп. Марта. Св. мчци Айтала и Амун дякони. Праведен Иисус Навин. Св. мчци Калист, Евод и Ермоген' WHERE service_date = '2026-09-01';
UPDATE services SET description = 'Св. мчк Мамант. Преп. Йоан постник, патриарх Константинополски. Св. 3628 мчци в Никомидия' WHERE service_date = '2026-09-02';
UPDATE services SET description = 'Св. свщмчк Антим, еп. Никомидийски. Преп. Теоктист. Св. Фива дякониса. Св. мчца Василиса Никомидийска. Св. Йоаникий II, патр. Сръбски. Пренасяне на св. мощи на св. Нектарий Егински' WHERE service_date = '2026-09-03';
UPDATE services SET description = 'Св. свщмчк Вавила, еп. Антиохийски. Св. пророк и боговидец Моисей. Св. мчца Ермиония. Преп. Петроний' WHERE service_date = '2026-09-04';
UPDATE services SET description = 'Св. прор. Захария и праведна Елисавета, родители на св. Йоан Предтеча' WHERE service_date = '2026-09-05';
UPDATE services SET description = '+ 14 Неделя след Петдесетница. Св. мчк Ромил. Св. мчк Евдоксий. Преп. Архип. Чудо на свети архангел Михаил в Колоса' WHERE service_date = '2026-09-06';
UPDATE services SET description = 'Св. мчк Созонт (Предпразненство на Рождество Богородично)' WHERE service_date = '2026-09-07';
UPDATE services SET description = '+ Рождество на Пресвета Богородица' WHERE service_date = '2026-09-08';
UPDATE services SET description = '*Св. праведни богоотци Йоаким и Анна. Св. Йоаким I, патриарх Търновски. Св. мчк Севириан' WHERE service_date = '2026-09-09';
UPDATE services SET description = 'Св. мчци Минодора, Митродора и Нимфодора' WHERE service_date = '2026-09-10';
UPDATE services SET description = 'Преп. Теодора Александрийска' WHERE service_date = '2026-09-11';
UPDATE services SET description = 'Св. свщмчк Автоном (Отдание на Рождество Богородично)' WHERE service_date = '2026-09-12';
UPDATE services SET description = '+ 15 Неделя след Петдесетница. Неделя преди Въздвижение. Обновление на храма на Свето Възкресение в Йерусалим. Св. свщмчк Корнилий стотник (Предпразненство на Въздвижение на Честния Кръст)' WHERE service_date = '2026-09-13';
UPDATE services SET description = '+ Въздвижение на Честния и Животворящ Кръст Господен (Кръстовден) (Строг пост)' WHERE service_date = '2026-09-14';
UPDATE services SET description = 'Св. вмчк Никита. Преп. Филотей. Св. мчк Леонид' WHERE service_date = '2026-09-15';
UPDATE services SET description = '*Св. вмчца Евфимия Всехвална. Св. Людмила Чешка. Св. Киприан, митр. Киевски и Московски, българин' WHERE service_date = '2026-09-16';
UPDATE services SET description = '*Св. мчци Вяра, Надежда и Любов и майка им София. Св. мчца Теодотия. Св. Нил, еп. Египетски' WHERE service_date = '2026-09-17';
UPDATE services SET description = 'Преп. Евмений, еп. Гортински чудотворец' WHERE service_date = '2026-09-18';
UPDATE services SET description = 'Св. мчци Трофим, Саватий и Доримедонт. (Събота след Въздвижение)' WHERE service_date = '2026-09-19';
UPDATE services SET description = '+ Неделя след Въздвижение. Св. вмчк Евстатий Плакида и семейството му' WHERE service_date = '2026-09-20';
UPDATE services SET description = 'Св. ап. Кодрат. Св. Исакий и Мелетий, еп. Кипърски (Отдание на Въздвижение)' WHERE service_date = '2026-09-21';
UPDATE services SET description = 'Преп. Козма Зографски. Св. свщмчк Фока, еп. Синопийски. Св. прор. Йона' WHERE service_date = '2026-09-22';
UPDATE services SET description = '*Зачатие на св. Йоан Предтеча и Кръстител. Св. мчца Ираида' WHERE service_date = '2026-09-23';
UPDATE services SET description = 'Св. първомъченица и равноапостолна Текла. Преп. Коприй. Св. Силуан Атонски' WHERE service_date = '2026-09-24';
UPDATE services SET description = '*Преп. Сергий, Радонежки чудотворец. Преп. Ефросиния Александрийска' WHERE service_date = '2026-09-25';
UPDATE services SET description = '*Успение на св. ап. и ев. Йоан Богослов. Утр. ев. Ин 21:15-25, ап. 1 Йоан. 4:12-19 (с. 389), лит. ев. Ин 19:25-27' WHERE service_date = '2026-09-26';
UPDATE services SET description = '+ 1 Неделя след Неделя подир Въздвижение. Св. мчк Калистрат и дружината му. Св. апостоли от 70-те Марк и Аристарх' WHERE service_date = '2026-09-27';
UPDATE services SET description = '*Преп. Харитон Изповедник. Св. прор. Варух' WHERE service_date = '2026-09-28';
UPDATE services SET description = 'Преп. Кириак Отшелник. Преп. Теофан Милостиви. Св. мчца Петрония' WHERE service_date = '2026-09-29';
UPDATE services SET description = 'Св. свщмчк Григорий, просветител на Армения. Св. мчца Рипсимия' WHERE service_date = '2026-09-30';
UPDATE services SET description = '*Покров на Пресвета Богородица. Св. ап. Анания. Преп. Роман Сладкопевец. Преп. Йоан Кукузел' WHERE service_date = '2026-10-01';
UPDATE services SET description = 'Св. свщмчк Киприан и св. мчца Юстина. Св. Андрей, юродив заради Христа' WHERE service_date = '2026-10-02';
UPDATE services SET description = 'Св. свщмчк Дионисий Ареопагит. Преп. Йоан Хозевит' WHERE service_date = '2026-10-03';
UPDATE services SET description = '+ 2 Неделя след Неделя подир Въздвижение. Св. свщмчк Йеротей, еп. Атински. Св. мчца Виринея. Преп. Павел Препрости' WHERE service_date = '2026-10-04';
UPDATE services SET description = 'Св. мчца Харитина. Св. свщмчк Дионисий, епископ Александрийски' WHERE service_date = '2026-10-05';
UPDATE services SET description = '*Св. апостол Тома' WHERE service_date = '2026-10-06';
UPDATE services SET description = 'Св. мчци Сергий и Вакх' WHERE service_date = '2026-10-07';
UPDATE services SET description = 'Преп. Пелагия. Св. прпмчк Игнатий Старозагорски' WHERE service_date = '2026-10-08';
UPDATE services SET description = '*Св. ап. Яков Алфеев. Преп. Андроник и Атанасия' WHERE service_date = '2026-10-09';
UPDATE services SET description = '*Св. 26 прпмчци Зографски. Св. мчци Евлампий и Евлампия. Преп. Теофил Изповедник' WHERE service_date = '2026-10-10';
UPDATE services SET description = '+ 4 Неделя след Неделя подир Въздвижение - на св. Отци от VII Вселенски събор. Св. апостол и дякон Филип. Преп. Теофан Начертаний, еп. Никейски' WHERE service_date = '2026-10-11';
UPDATE services SET description = 'Св. мчци Пров, Тарах и Андроник. Преп. Козма, епископ Маюмски. Св. Мартин Милостиви' WHERE service_date = '2026-10-12';
UPDATE services SET description = 'Св. мчци Карп и Папила. Св. мчк Флорентий. Св. мчк Вениамин, дякон' WHERE service_date = '2026-10-13';
UPDATE services SET description = '*Преп. Параскева - Петка Търновска (Петковден). Св. мчци Назарий, Гервасий, Протасий и Целсий' WHERE service_date = '2026-10-14';
UPDATE services SET description = 'Преп. Евтимий Нови. Св. Лукиан, презв. Антиохийски' WHERE service_date = '2026-10-15';
UPDATE services SET description = 'Св. мчк Лонгин стотник. Преп. Мала Отшелник' WHERE service_date = '2026-10-16';
UPDATE services SET description = 'Св. прор. Осия. Св. прпмчк Андрей Критски' WHERE service_date = '2026-10-17';
UPDATE services SET description = '+ 3 Неделя след Неделя подир Въздвижение. Св. ап. и ев. Лука. Св. вмчца Злата Мъгленска' WHERE service_date = '2026-10-18';
UPDATE services SET description = '+ Преп. Йоан Рилски Чудотворец. Св. прор. Йоил. Св. мчк Уар' WHERE service_date = '2026-10-19';
UPDATE services SET description = 'Св. мчк Артемий Антиохийски' WHERE service_date = '2026-10-20';
UPDATE services SET description = '*Преп. Иларион Велики. Св. Иларион, еп. Мъгленски' WHERE service_date = '2026-10-21';
UPDATE services SET description = '*Прославление на св. мощи на св. Евтимий, патриарх Търновски. Св. равноап. Аверкий, еп. Йераполски чудотворец' WHERE service_date = '2026-10-22';
UPDATE services SET description = '*Св. ап. Яков, брат Божий' WHERE service_date = '2026-10-23';
UPDATE services SET description = '*Св. Богородица „Всех скорбящих радост”. (Молебен за децата с увреждания). Св. мчк Арета' WHERE service_date = '2026-10-24';
UPDATE services SET description = '+ 6 Неделя след Неделя подир Въздвижение. Св. мчци Маркиан и Мартирий' WHERE service_date = '2026-10-25';
UPDATE services SET description = '+ Св. вмчк Димитрий Мироточиви (Димитровден). Преп. Димитра Киевска (Доростолска)' WHERE service_date = '2026-10-26';
UPDATE services SET description = '*Св. мчк Нестор. Преп. Димитрий Басарбовски' WHERE service_date = '2026-10-27';
UPDATE services SET description = '*Св. мчца Параскева. Св. мчци Терентий, Неонила и чедата им. Преп. Стефан Саваит. Св. Димитрий, митр. Ростовски. Преп. Теофана (царица Теодора Българска)' WHERE service_date = '2026-10-28';
UPDATE services SET description = 'Св. прпмчца Анастасия Римлянка. Преп. Серапион' WHERE service_date = '2026-10-29';
UPDATE services SET description = '*Св. крал Стефан Милутин. Св. свщмчк Зиновий, еп. Егейски и св. мчца Зиновия' WHERE service_date = '2026-10-30';
UPDATE services SET description = 'Св. апли от 70-те: Стахий, Амплий и др. Св. мчк Епимах' WHERE service_date = '2026-10-31';
UPDATE services SET description = '+ 5 Неделя след Неделя подир Въздвижение. Св. безср. и чудотворци Козма и Дамян. Св. прпмчци Яков Костурски, дякон Яков и монах Дионисий' WHERE service_date = '2026-11-01';
UPDATE services SET description = 'Св. мчци Акиндин, Пигасий, Афтоний, Елпидифор и Анемподист' WHERE service_date = '2026-11-02';
UPDATE services SET description = '*Преп. Пимен Зографски (Софийски). Св. свщмчци Акепсим, Йосиф и Айтал' WHERE service_date = '2026-11-03';
UPDATE services SET description = 'Преп. Йоаникий Велики. Св. свщмчци Никандър, епископ Мирски и Ермей презвитер' WHERE service_date = '2026-11-04';
UPDATE services SET description = 'Св. мчци Галактион и Епистима' WHERE service_date = '2026-11-05';
UPDATE services SET description = 'Св. Павел, архиеп. Константинополски. Св. Клавдия. Преп. Лука Тавроменийски' WHERE service_date = '2026-11-06';
UPDATE services SET description = 'Св. 33 мчци в Мелитин. Преп. Лазар Галисийски. (Задушница)' WHERE service_date = '2026-11-07';
UPDATE services SET description = '+ 7 Неделя след Неделя подир Въздвижение. Събор на св. архангел Михаил. Св. мчк Ангел Лерински. (Архангеловден) Гл. 6, утр. ев. 1, ап. Ефес. 2:4-10 (с.224), лит. ев. Лк 8:41-56 (с.127) [на Архангелите: ап. Евр. 2:2-10 (с. 408), лит. ев. Лк 10: 16-21(с. 275)]' WHERE service_date = '2026-11-08';
UPDATE services SET description = '*Св. Нектарий, еп. Егински, чудотворец. Св. мчци Онисифор и Порфирий. Преп. Матрона и Теоктиста' WHERE service_date = '2026-11-09';
UPDATE services SET description = 'Св. апли Ераст, Олипм и Родион. Преп. Арсений Кападокийски' WHERE service_date = '2026-11-10';
UPDATE services SET description = '*Св. мчк Мина. Св. мчци Виктор и Стефанида. Св. мчк дякон Викентий. Преп. Теодор Студит, изповедник' WHERE service_date = '2026-11-11';
UPDATE services SET description = 'Св. Йоан Милостиви, патр. Александрийски. Преп. Нил Постник. Преп. Нил Мироточиви, Атонски. Св. прор. Ахия' WHERE service_date = '2026-11-12';
UPDATE services SET description = '*Св. Йоан Златоуст, архиеп. Константинополски' WHERE service_date = '2026-11-13';
UPDATE services SET description = '*Св. ап. Филип. Св. благоверни цар Управда-Юстиниан. Св. мчк Константин от Идра (Рождественски заговезни)' WHERE service_date = '2026-11-14';
UPDATE services SET description = '+ 8 Неделя след Неделя подир Въздвижение. Св. мчци Гурий, Самон и Авив' WHERE service_date = '2026-11-15';
UPDATE services SET description = '*Свети апостол и евангелист Матей' WHERE service_date = '2026-11-16';
UPDATE services SET description = 'Св. Григорий Неокесарийски, чудотворец' WHERE service_date = '2026-11-17';
UPDATE services SET description = 'Св. мчци Платон, Роман дякон и Варух отрок' WHERE service_date = '2026-11-18';
UPDATE services SET description = 'Св. прор. Авдий. Св. мчк Варлаам' WHERE service_date = '2026-11-19';
UPDATE services SET description = 'Преп. Григорий Декаполит. Св. Прокъл, архиепископ Константинополски. Св. мчк Дасий Доростолски. (Предпразненство на Въведение Богородично)' WHERE service_date = '2026-11-20';
UPDATE services SET description = '+ Въведение Богородично (Ден на православната християнска младеж и семейство) (Разрешава се риба)' WHERE service_date = '2026-11-21';
UPDATE services SET description = '+ 9 Неделя след Неделя подир Въздвижение. Св. ап. Филимон. Св. Михаил воин, българин' WHERE service_date = '2026-11-22';
UPDATE services SET description = '*Св. благоверен княз Александър Невски. Св. Амфилохий, еп. Иконийски. Св. Григорий, еп. Акрагантийски' WHERE service_date = '2026-11-23';
UPDATE services SET description = '*Св. вмчца Екатерина. Св. вмчк Меркурий' WHERE service_date = '2026-11-24';
UPDATE services SET description = '*Св. Климент, папа Римски, пръв епископ на Сердика. Св. Климент, архиеп. Охридски. Св. Петър, еп. Александрийски (Отдание на Въведение Богородично)' WHERE service_date = '2026-11-25';
UPDATE services SET description = '*Св. Стилиан Пафлагонийски. Преп. Алипий Стълпник. Преп. Яков Отшелник' WHERE service_date = '2026-11-26';
UPDATE services SET description = '*Преп. Теодосий Търновски. Св. вмчк Яков Персиец. Преп. Паладий' WHERE service_date = '2026-11-27';
UPDATE services SET description = 'Св. прпмчк Стефан Нови. Св. мчк Иринарх. Св. 15 свщмчци Тивериополски. Св. мчк Христо, българин. Препмчци Сократ и Комасий' WHERE service_date = '2026-11-28';
UPDATE services SET description = '+ 13 Неделя след Неделя подир Въздвижение. Св. мчк Парамон и 370 мъченици. Св. мчк Филумен. Преп. Акакий Синайски' WHERE service_date = '2026-11-29';
UPDATE services SET description = '*Св. ап. Андрей Първозвани (Андреевден)' WHERE service_date = '2026-11-30';
UPDATE services SET description = 'Св. прор. Наум. Св. Филарет Милостиви' WHERE service_date = '2026-12-01';
UPDATE services SET description = '*Св. Порфирий Кавсокаливит. Св. прор. Авакум. Преп. Йоан и Андрей' WHERE service_date = '2026-12-02';
UPDATE services SET description = 'Св. прор. Софония. Св. свщмчк Теодор, архиепископ Александрийски' WHERE service_date = '2026-12-03';
UPDATE services SET description = '*Св. вмчца Варвара. Преп. Йоан Дамаскин' WHERE service_date = '2026-12-04';
UPDATE services SET description = '*Преп. Сава Освещени. Преп. Нектарий Битолски' WHERE service_date = '2026-12-05';
UPDATE services SET description = '+ 10 Неделя след Неделя подир Въздвижение. Св. Николай, архиеп. Мирликийски, Чудотворец (Никулден)' WHERE service_date = '2026-12-06';
UPDATE services SET description = 'Св. Амвросий, еп. Медиолански. Св. Филотея Търновска. Преп. Герасим Микраянанит - Химнописец' WHERE service_date = '2026-12-07';
UPDATE services SET description = 'Преп. Патапий' WHERE service_date = '2026-12-08';
UPDATE services SET description = '*Зачатие на св. Анна. Св. Анна, майка на пророк Самуил' WHERE service_date = '2026-12-09';
UPDATE services SET description = 'Св. мчци Мина, Ермоген и Евграф' WHERE service_date = '2026-12-10';
UPDATE services SET description = '*Преп. Даниил Стълпник. Преп. Лука Стълпник' WHERE service_date = '2026-12-11';
UPDATE services SET description = '*Св. Спиридон, еп. Тримитунтски Чудотворец' WHERE service_date = '2026-12-12';
UPDATE services SET description = '+ 11 Неделя след Неделя подир Въздвижение - на св. Праотци. Св. мчци Евстратий, Авксентий, Евгений, Мардарий и Орест. Св. мчца Лукия девица' WHERE service_date = '2026-12-13';
UPDATE services SET description = 'Св. мчци Тирс, Левкий, Филимон, Ариан и Калиник' WHERE service_date = '2026-12-14';
UPDATE services SET description = 'Св. свщмчк Елевтерий. Преп. Павел Латрийски. Св. Стефан, изповедник' WHERE service_date = '2026-12-15';
UPDATE services SET description = 'Св. прор. Агей. Св. мчк Марин' WHERE service_date = '2026-12-16';
UPDATE services SET description = 'Св. прор. Даниил и св. 3 отроци Анания, Азария и Мисаил' WHERE service_date = '2026-12-17';
UPDATE services SET description = 'Св. Модест, патр. Йерусалимски. Св. мчк Севастиан и дружината му' WHERE service_date = '2026-12-18';
UPDATE services SET description = 'Св. мчк Бонифаций. Св. Бонифаций, еп. Ферентийски. Св. Григорий, еп. Омиритски. Св. свщмчк Игнатий Богоносец (Игнажден)' WHERE service_date = '2026-12-19';
UPDATE services SET description = '+ Неделя преди Рождество Христово. (Предпразненство на Рождество Христово) Св. Йоан Кронщадски' WHERE service_date = '2026-12-20';
UPDATE services SET description = 'Св. мчца Юлиания и пострадали с нея 500 мъже и 130 жени в Никомидия' WHERE service_date = '2026-12-21';
UPDATE services SET description = 'Св. вмчца Анастасия' WHERE service_date = '2026-12-22';
UPDATE services SET description = '*Преп. Наум Охридски. Св. 10 мчци в Крит. Св. мчк Геласий' WHERE service_date = '2026-12-23';
UPDATE services SET description = 'Св. прпмчца Евгения. Преп. Николай воин, българин (Утреня, Царски часове, Вечерня със св. Вас. лит.) (Бъдни вечер)' WHERE service_date = '2026-12-24';
UPDATE services SET description = '+ Рождество Христово (Всичко на празника) (Утреня и св. Злат. лит.) (Блажи се)' WHERE service_date = '2026-12-25';
UPDATE services SET description = '+ Събор на Пресвета Богородица. Св. Йосиф Обручник. Св. цар Давид. Св. Яков, брат Господен' WHERE service_date = '2026-12-26';
UPDATE services SET description = '+ Неделя след Рождество Христово. Св. първомъченик и архидякон Стефан. Преп. Теодор Начертаний (Стефановден)' WHERE service_date = '2026-12-27';
UPDATE services SET description = 'Св. 20 хиляди мъченици, изгорени в Никомидия' WHERE service_date = '2026-12-28';
UPDATE services SET description = 'Св. 14 хиляди младенци-мъченици, избити от Ирод във Витлеем. Преп. Маркел' WHERE service_date = '2026-12-29';
UPDATE services SET description = 'Св. мчца Анисия. Свщмчк Зотик Сиропитател. Преп. Теодора Кесарийска. Преп. Теодора Константинополска (Блажи се)' WHERE service_date = '2026-12-30';
UPDATE services SET description = 'Преп. Мелания Римлянка (Отдание на Рождество Христово)' WHERE service_date = '2026-12-31';
